Use correct snprintf sizeof variable
Clang reports a problem with the variable being used to calculate the
size of the string buffer in XrdSsiFileReq::Alloc -

    XrdSsiFileReq.cc:142:33: error: invalid use of member 'rID' in static member

The fix is to use sizeof() on the same variable that is receiving the string.