[CMake] Remove XRootDCommon.cmake
This module is hacky, so remove it. In particular, the call to
include_directories(../ ./ ...) adds the top directory of the
project to the list of includes, and on macOS where there is no
case-sensitivity, "#include <version>" somewhere includes the newly
added VERSION file with git information and causes compilation to
fail with the error below:

/Users/runner/work/xrootd/xrootd/src/../version:1:1:
  error: unknown type name '$Format'
$Format:%(describe)$
^
/Users/runner/work/xrootd/xrootd/src/../version:1:8:
  error: expected unqualified-id
$Format:%(describe)$
       ^