Add installation of missing header XrdCl/XrdClOptional.hh
XrdClOptional.hh is included in public header file
XrdClPlugInInterface.hh :
/home/oksana/CERN/xrootd-HEAD/include/xrootd/XrdCl/XrdClPlugInInterface.hh:30:10: fatal error: XrdCl/XrdClOptional.hh: No such file or directory
   30 | #include XrdCl/XrdClOptional.hh