[XrdHttpTpc] Replace forward declaration with header inclusion for XrdSfsFile
Needed because class Stream needs a std::unique_ptr<XrdSfsFile>, which is only
forward declared. This change addresses the static analysis error below.

[ 70%] Building CXX object src/XrdHttpTpc/CMakeFiles/XrdHttpTPC-5.dir/XrdHttpTpcStream.cc.o
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/unique_ptr.h:91:16:
 error: invalid application of 'sizeof' to an incomplete type 'XrdSfsFile'
   91 |         static_assert(sizeof(_Tp)>0,
      |                       ^~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/unique_ptr.h:399:4:
 note: in instantiation of member function 'std::default_delete<XrdSfsFile>::operator()' requested here
  399 |           get_deleter()(std::move(__ptr));
      |           ^
xrootd/src/XrdHttpTpc/XrdHttpTpcStream.hh:24:5:
 note: in instantiation of member function 'std::unique_ptr<XrdSfsFile>::~unique_ptr' requested here
   24 |     Stream(std::unique_ptr<XrdSfsFile> fh, size_t max_blocks, size_t buffer_size, XrdSysError &log)
      |     ^
src/xrootd/src/XrdHttpTpc/XrdHttpTpcStream.hh:18:7: note: forward declaration of 'XrdSfsFile'
   18 | class XrdSfsFile;
      |       ^
1 error generated.
Error while processing xrootd/src/XrdHttpTpc/XrdHttpTpcStream.cc.