The latest updates to glibc headers adds __nonnull to the fclose()
Declaration in old version:

extern int fclose (FILE *__stream);

Declaration in new version:

extern int fclose (FILE *__stream) __nonnull ((1));

This change causes a compilation error in xrootd:

/builddir/build/BUILD/xrootd-5.5.5/src/XrdTls/XrdTlsTempCA.cc:54:48: error: ignoring attributes on template argument 'int (*)(FILE*)' [-Werror=ignored-attributes]
   54 | typedef std::unique_ptr<FILE, decltype(&fclose)> file_smart_ptr;
      |                                                ^

This commit rewrites the code so the error is not triggered.