[XrdPosix] Fix build with Clang and _FORTIFY_SOURCE enabled
Some of the checks added by defining _FORTIFY_SOURCE break the
build with clang with errors like the one shown below. See the
manual page for feature_test_macros(7) for more information.

xrootd/src/XrdPosix/XrdPosixPreload32.cc:375:9:
  error: redefinition of a 'extern inline' function 'pread' is not supported in C++
ssize_t pread(int fildes, void *buf, size_t nbyte, off_t offset)
        ^
/usr/include/bits/unistd.h:72:1: note: previous definition is here
pread (int __fd, void *__buf, size_t __nbytes, __off_t __offset)
^

Since distributions enable _FORTIFY_SOURCE by default, it's better
to disable it for the XrdPosix plugin when using clang. Builds with
GCC are not affected by this problem.

Fixes #1975.