Fix compilation failure on 32 bit (ix86/arm32)
src/XrdOfs/XrdOfs.cc:
error: format '%ld' expects argument of type 'long int',
but argument 4 has type 'off_t' {aka 'long long int'} [-Werror=format=]

src/XrdSfs/XrdSfsInterface.cc:
Type changed from ssize_t (32/64 bits) to off_t (64 bits)
Change cast from (long) to (long long) and format from %ld to %lld