python bindings: catch ReferenceError error when finalizing File's
The finalize method iterates over all references known to the garbage
collector, even those not created by the xrootd bindings. This does not
work correctly when the target of a weak reference has been already
collected.

This pr catches this exception, e.g.:

Traceback (most recent call last):
  File
  ".../envs/topcoffea-env/lib/python3.8/site-packages/XRootD/client/finalize.py",
  line 46, in finalize
      if isinstance(obj, File) and obj.is_open():
ReferenceError: weakly-referenced object no longer exists