Work around inconsistent type definitions on MIPS
The st_rdev field in struct stat (which is 32 bits) is not type dev_t
(which is 64 bits)

/<<PKGBUILDDIR>>/src/XrdPosix/XrdPosixAdmin.cc:188:45: error: cannot convert ‘long unsigned int*’ to ‘dev_t*’ {aka ‘long long unsigned int*’}
  188 |    Stat.st_mode   = XrdPosixMap::Flags2Mode(&Stat.st_rdev, sInfo->GetFlags());
      |                                             ^~~~~~~~~~~~~
      |                                             |
      |                                             long unsigned int*
In file included from /<<PKGBUILDDIR>>/src/XrdPosix/XrdPosixAdmin.cc:38:
/<<PKGBUILDDIR>>/src/./XrdPosix/XrdPosixMap.hh:43:46: note:   initializing argument 1 of ‘static mode_t XrdPosixMap::Flags2Mode(dev_t*, uint32_t)’
   43 | static mode_t              Flags2Mode(dev_t *rdv, uint32_t flags);
      |                                       ~~~~~~~^~~
make[4]: *** [src/CMakeFiles/XrdPosix.dir/build.make:85: src/CMakeFiles/XrdPosix.dir/XrdPosix/XrdPosixAdmin.cc.o] Error 1