[XrdCl] Move class Operations before PipelineHandler
This change is to fix the following error from static analysis:

/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/unique_ptr.h:91:16:
error: implicit instantiation of undefined template 'XrdCl::Operation<true>'
   91 |         static_assert(sizeof(_Tp)>0,
      |                       ^
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/unique_ptr.h:399:4:
note: in instantiation of member function 'std::default_delete<XrdCl::Operation<true>>::operator()' requested here
  399 |           get_deleter()(std::move(__ptr));
      |           ^
xrootd/src/XrdCl/XrdClOperations.hh:79:7: note: in instantiation of member function
 'std::unique_ptr<XrdCl::Operation<true>>::~unique_ptr' requested here
   79 |       PipelineHandler()
      |       ^
xrootd/src/XrdCl/XrdClOperations.hh:49:32: note: template is declared here
   49 |   template<bool HasHndl> class Operation;
      |                                ^
1 error generated.
Error while processing xrootd/src/XrdCl/XrdClFileStateHandler.cc.

The problem is that PipelineHandler has a std::unique_ptr<XrdCl::Operation<true>>
as a member, but the type XrdCl::Operation<true> is not yet fully known by the compiler.
Moving the class definition for Operation before PipelineHandler makes the type known to
the compiler by the time it reaches the member declaration in PipelineHandler. However,
since class Operation uses PipelineHandler as well, some methods had to be outlined and
moved towards the end of the header file.