Reapply the fix to tests/XrdClTests/LocalFileHandlerTest.cc also to tests/XrdCl/XrdClLocalFileHandlerTest.cc
Original commit message:

OpenFlags::Flags should not be used for the flags argument in a posix
open() call, since they use different values.

The OpenFlags::Flags values are defined in src/XrdCl/XrdClFileSystem.hh:

    MakePath = kXR_mkpath,        //!< Create directory path if it does not
                                  //!< already exist
    New      = kXR_new,           //!< Open the file only if it does not already
    Update   = kXR_open_updt,     //!< Open for reading and writing

The kXR_* values are defined in src/XProtocol/XProtocol.hh:
    kXR_new      = 0x0008, //     8
    kXR_mkpath   = 0x0100, //   256
    kXR_open_updt= 0x0020, //    32

As can be seen these do not correspond to the O_* values used in the
posix open() call. What they actually mean depends on the system and
varies between architectures.

On hppa Linux O_CREAT is defind in /usr/include/hppa-linux-gnu/asm/fcntl.h:

    #define O_CREAT		000000400 /* not fcntl */

Since 0o400 = 0x100 = 256 this by chance matches kXR_mkpath and
triggers the error below. On other architectures the wrong flags are
just silently accepted.

In file included from /usr/include/fcntl.h:342,
                 from /<<PKGBUILDDIR>>/tests/XrdClTests/LocalFileHandlerTest.cc:25:
In function ‘int open(const char*, int, ...)’,
    inlined from ‘void LocalFileHandlerTest::WriteMkdirTest()’ at /<<PKGBUILDDIR>>/tests/XrdClTests/LocalFileHandlerTest.cc:210:17:
/usr/include/hppa-linux-gnu/bits/fcntl2.h:50:31: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
   50 |           __open_missing_mode ();
      |           ~~~~~~~~~~~~~~~~~~~~^~